# Generated by Django 6.0.3 on 2026-04-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='selling_price_local',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
